version: '3'
services:
  zookeeper1:
    image: 'confluentinc/cp-zookeeper:5.0.0'
    restart: always
    container_name: zookeeper1
    network_mode: "container:pause_container"
    ipc: "container:pause_container"
    pid: "container:pause_container"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      COMPONENT: zookeeper
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker1:
    image: 'confluentinc/cp-kafka:5.0.0'
    stop_grace_period: 120s
    container_name: kafka_broker_1
    depends_on:
    - zookeeper1
    network_mode: "container:pause_container"
    ipc: "container:pause_container"
    pid: "container:pause_container"
    environment:
      COMPONENT: kafka
      KAFKA_BROKER_ID: 1001
      KAFKA_RESERVED_BROKER_MAX_ID: 10000
      KAFKA_ZOOKEEPER_CONNECT: 'localhost:2181'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

  broker2:
    image: 'confluentinc/cp-kafka:5.0.0'
    stop_grace_period: 120s
    container_name: kafka_broker_2
    depends_on:
    - zookeeper1
    network_mode: "container:pause_container"
    ipc: "container:pause_container"
    pid: "container:pause_container"
    environment:
      COMPONENT: kafka
      KAFKA_BROKER_ID: 1002
      KAFKA_RESERVED_BROKER_MAX_ID: 10000
      KAFKA_ZOOKEEPER_CONNECT: 'localhost:2181'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:9093'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'


  broker3:
    image: 'confluentinc/cp-kafka:5.0.0'
    stop_grace_period: 120s
    container_name: kafka_broker_3
    depends_on:
    - zookeeper1
    network_mode: "container:pause_container"
    ipc: "container:pause_container"
    pid: "container:pause_container"
    environment:
      COMPONENT: kafka
      KAFKA_BROKER_ID: 1003
      KAFKA_RESERVED_BROKER_MAX_ID: 10000
      KAFKA_ZOOKEEPER_CONNECT: 'localhost:2181'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:9094'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
